"""Rename program_distribution classification code to major_distribution.

The business term is "专业布点数", but the stable machine code should use
``major`` rather than ``program`` to match the NEXUS major-domain naming.
This migration updates already-seeded GovernanceRulesVersion JSONB content;
new seeds are generated by ``seed_data._build_code`` with the same code.

Revision ID: 20260628_0055
Revises: 20260626_0054
Create Date: 2026-06-28
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260628_0055"
down_revision: str | None = "20260626_0054"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        sa.text(
            """
            UPDATE governance_rules_version
            SET rules_content = replace(
                    rules_content::text,
                    '"program_distribution"',
                    '"major_distribution"'
                )::jsonb,
                updated_at = now()
            WHERE rules_content::text LIKE '%"program_distribution"%'
            """
        )
    )


def downgrade() -> None:
    op.execute(
        sa.text(
            """
            UPDATE governance_rules_version
            SET rules_content = replace(
                    rules_content::text,
                    '"major_distribution"',
                    '"program_distribution"'
                )::jsonb,
                updated_at = now()
            WHERE rules_content::text LIKE '%"major_distribution"%'
            """
        )
    )
