"""Auth P1 enablement — JWT user login, api-caller revocation, soft-delete, cancel signal.

Revision ID: 20260603_0018
Revises: 20260601_0017
Create Date: 2026-06-03

Changes:
- user_account: + password_hash
- api_caller: + caller_key_hash (sha256 hex, unique), + revoked_at, drop unique on
  caller_key; backfill caller_key_hash from existing caller_key.
- data_source: + deleted_at (soft-delete tombstone)
- job: + cancel_requested_at (operator cancel signal honored by worker)
- new table refresh_token: backs the JWT refresh flow (jti, user_id, expires_at,
  revoked_at, parent_jti).
"""

import hashlib
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260603_0018"
down_revision: str | None = "20260601_0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ── user_account.password_hash ────────────────────────────────────────
    op.add_column(
        "user_account",
        sa.Column("password_hash", sa.String(length=255), nullable=True),
    )

    # ── api_caller: add hash + revoked_at; drop unique on caller_key ──────
    op.add_column(
        "api_caller",
        sa.Column("caller_key_hash", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "api_caller",
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
    )

    # Backfill caller_key_hash for existing rows.
    bind = op.get_bind()
    rows = bind.execute(
        sa.text("SELECT id, caller_key FROM api_caller WHERE caller_key IS NOT NULL")
    ).fetchall()
    for row in rows:
        digest = hashlib.sha256(row.caller_key.encode("utf-8")).hexdigest()
        bind.execute(
            sa.text("UPDATE api_caller SET caller_key_hash = :h WHERE id = :i"),
            {"h": digest, "i": row.id},
        )

    op.alter_column("api_caller", "caller_key", existing_type=sa.String(length=80), nullable=True)
    # Older schema had a UNIQUE on api_caller.caller_key; the constraint name
    # varies across deployments (autogenerated). Try the conventional name; if
    # it doesn't exist we still want to create the new unique on caller_key_hash.
    try:
        op.drop_constraint("api_caller_caller_key_key", "api_caller", type_="unique")
    except Exception:
        pass
    op.create_unique_constraint(
        "uq_api_caller_caller_key_hash", "api_caller", ["caller_key_hash"]
    )

    # ── data_source.deleted_at ────────────────────────────────────────────
    op.add_column(
        "data_source",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )

    # ── job.cancel_requested_at ───────────────────────────────────────────
    op.add_column(
        "job",
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
    )

    # ── refresh_token table ───────────────────────────────────────────────
    op.create_table(
        "refresh_token",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column(
            "user_id",
            sa.String(length=36),
            sa.ForeignKey("user_account.id"),
            nullable=False,
        ),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parent_jti", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("jti", name="uq_refresh_token_jti"),
    )
    op.create_index("ix_refresh_token_user_id", "refresh_token", ["user_id"])
    op.create_index("ix_refresh_token_expires_at", "refresh_token", ["expires_at"])


def downgrade() -> None:
    op.drop_index("ix_refresh_token_expires_at", table_name="refresh_token")
    op.drop_index("ix_refresh_token_user_id", table_name="refresh_token")
    op.drop_table("refresh_token")

    op.drop_column("job", "cancel_requested_at")
    op.drop_column("data_source", "deleted_at")

    op.drop_constraint("uq_api_caller_caller_key_hash", "api_caller", type_="unique")
    try:
        op.create_unique_constraint(
            "api_caller_caller_key_key", "api_caller", ["caller_key"]
        )
    except Exception:
        pass
    op.alter_column(
        "api_caller", "caller_key", existing_type=sa.String(length=80), nullable=False
    )
    op.drop_column("api_caller", "revoked_at")
    op.drop_column("api_caller", "caller_key_hash")

    op.drop_column("user_account", "password_hash")
